#!/bin/bash

# Path to your CME executable
CME_PATH="/usr/bin/crackmapexec"

# Path to the report file generated by your Ruby parser
REPORT_FILE="/home/kali/discovery/services/Reports/microsoft.txt"

# Loop through each line in the report file
while IFS= read -r line; do
    # Extract relevant information from the line (modify this according to your report format)
    ip=$(echo "$line" | awk '{print $1}')
    port=$(echo "$line" | awk '{print $2}')
    
    # Run CME in SMB mode for the extracted IP and port
    $CME_PATH smb $ip -p $port
    
    # You can add more options or actions here if needed
    
done < "$REPORT_FILE"
