#!/usr/bin/env ruby
#############################
# Author = Royce Davis
# Last edited February 2, 2011
#############################
require 'rubygems'
require 'nmap/parser'

unless ARGV.length > 0
  puts "Generates a .txt file containing the open ports summary and the .nmap information\r\n"
  puts "USAGE:\t./parsenmap <nmap xml file>\r\n\n"
  exit!
end

def current_datetime
  Time.now.strftime("%Y-%m-%d_%H-%M-%S")
end

nmap_file = ARGV[0]
output_file = "Report_#{File.basename(nmap_file, '.xml')}_#{current_datetime}.txt"

ports = Array.new
portstring = String.new
result_string = String.new
parser = Nmap::Parser.parsefile(nmap_file)

parser.hosts("up") do |host|
  [:tcp, :udp].each do |type|
    host.getports(type, "open") do |port|
      string = port.state.to_s
      unless string.include? "filtered"
        srv = port.service
        ports << port.num unless ports.include? port.num
        result_string << "#{host.addr}\t#{port.num}\t#{srv.name}\t#{srv.product}\t#{srv.version}\t#{srv.extrainfo}\n"
      end
    end
  end
end

puts result_string

File.open(output_file, "w") do |file|
  file.write(result_string)
end

ports.each { |port| portstring << port.to_s + "," }
puts "Results saved to #{output_file}"
puts "sudo nmap -sS -p #{portstring.chop} -sV -A -vv -oA enumeration -iL ../ranges.txt"

