#!/usr/bin/env ruby
#############################
# Author = Royce Davis, Alexander Alexandrov
# Last edited August 8, 2023
#############################
require 'rubygems'
require 'nmap/parser'
require 'fileutils'

unless ARGV.length > 0
  puts "Generates a .txt file containing the open ports summary and the .nmap information\r\n"
  puts "USAGE:\t./parsenmap <nmap xml file>\r\n\n"
  exit!
end

def current_datetime
  Time.now.strftime("Date_%Y-%m-%d_%H-%M-%S")
end

nmap_file = ARGV[0]
output_directory = "Reports"
FileUtils.mkdir_p(output_directory) unless Dir.exist?(output_directory)

parser = Nmap::Parser.parsefile(nmap_file)

parser.hosts("up") do |host|
  [:tcp, :udp].each do |type|
    host.getports(type, "open") do |port|
      string = port.state.to_s
      unless string.include? "filtered"
        srv = port.service
        output_file = "#{output_directory}/Report_#{srv.name}_#{current_datetime}.txt"
        
        result_string = "#{host.addr}\t#{port.num}\t#{srv.name}\t#{srv.product}\t#{srv.version}\t#{srv.extrainfo}\n"

        File.open(output_file, "a") do |file|
          file.write(result_string)
        end
      end
    end
  end
end

puts "Results saved to #{output_directory}"
